correction

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,3 +1,16 @@
-#!/bin/bash/python3
-python3 $PYFILE
+#!/bin/bash
 
+# Check if the $PYFILE environment variable is set
+if [ -z "$PYFILE" ]; then
+  echo "Error: PYFILE environment variable is not set."
+  exit 1
+fi
+
+# Check if the file specified in $PYFILE exists
+if [ ! -f "$PYFILE" ]; then
+  echo "Error: $PYFILE does not exist."
+  exit 1
+fi
+
+# Run the Python script using the `python3` command
+python3 $PYFILE
